# Generated by Django 6.1.1 on 2026-09-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Interface', '0002_varificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='varificationcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
