# Generated by Django 6.1.1 on 2026-09-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Interface', '0003_varificationcode_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
    ]
