# Generated by Django 6.1.1 on 2026-09-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='one_time_password',
            field=models.BooleanField(default=False),
        ),
    ]
