# Generated by Django 6.1.1 on 2026-09-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_Admin', '0002_adminprofile_one_time_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainschedule',
            name='ticket_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
