# Generated by Django 6.1.1 on 2026-09-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_Admin', '0003_trainschedule_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainticket',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
    ]
