# Generated by Django 6.1.1 on 2026-09-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_Admin', '0004_alter_trainticket_seat_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainschedule',
            old_name='ticket_price',
            new_name='ac_ticket_price',
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='s_chair_ticket_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='singdha_ticket_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
