# Generated by Django 6.1.1 on 2026-09-28 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_Admin', '0005_rename_ticket_price_trainschedule_ac_ticket_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='booking_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddConstraint(
            model_name='trainticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('train_schedule', 'seat_number'), name='unique_booked_seat_per_schedule'),
        ),
    ]
