# Generated by Django 6.1.1 on 2026-09-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_Admin', '0006_trainticket_user_alter_trainticket_booking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainticket',
            name='confirmation_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
