# Generated by Django 6.1.1 on 2026-09-29 13:31

from django.conf import settings
from django.db import migrations, models


def preserve_existing_payments(apps, schema_editor):
    TicketPayment = apps.get_model('Railway_Admin', 'TicketPayment')
    for payment in TicketPayment.objects.all().iterator():
        payment.tickets.add(payment.ticket_id)


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_Admin', '0008_ticketpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trainticket',
            name='unique_booked_seat_per_schedule',
        ),
        migrations.AddField(
            model_name='ticketpayment',
            name='tickets',
            field=models.ManyToManyField(related_name='payments', to='Railway_Admin.trainticket'),
        ),
        migrations.RunPython(preserve_existing_payments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='ticketpayment',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticketpayment',
            name='status',
            field=models.CharField(default='paid', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticketpayment',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketpayment',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='trainticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'booked'))), fields=('train_schedule', 'seat_number'), name='unique_booked_seat_per_schedule'),
        ),
    ]
