# Generated by Django 6.1.1 on 2026-10-01 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_Admin', '0009_remove_trainticket_unique_booked_seat_per_schedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trainticket',
            index=models.Index(fields=['status', 'booking_time'], name='tt_status_btime_idx'),
        ),
        migrations.AddIndex(
            model_name='trainticket',
            index=models.Index(fields=['user', 'status', 'booking_time'], name='tt_user_status_btime_idx'),
        ),
    ]
