# Generated by Django 6.1.1 on 2026-10-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railway_Admin', '0010_trainticket_tt_status_btime_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trainschedule',
            index=models.Index(fields=['departure_time'], name='ts_departure_idx'),
        ),
    ]
